import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  /**
   * Sidebar shows only **Guru card contents** and **SOP** (main).
   * Other top-level docs (Tutorial Intro, Review Response Management, etc.)
   * stay in `docs/` and remain buildable; open via direct URL if needed.
   */
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Guru card contents',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'guru-card-contents'}],
    },
    {
      type: 'category',
      label: 'SOP',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'sop'}],
    },
  ],
};

export default sidebars;
